# Main configuration file for SFT training
defaults:
  - dataset: default
  - model: qwen2.5-3b
  - training: default
  - _self_

# Output directory for model checkpoints and logs
output_dir: outputs/sft-arithmetic-model

# Random seed for reproducibility
seed: 42
