# Main configuration file for GRPO training
defaults:
  - dataset: default
  - model: qwen2.5-3b
  - training: default
  - _self_

# Output directory for model checkpoints and logs
output_dir: models/grpo

# Resume from checkpoint
resume_from_checkpoint: models/sft

# Random seed for reproducibility
seed: 42
