# Qwen2.5-3B model configuration

# Hugging Face model identifier
model_id: Qwen/Qwen2.5-3B-Instruct

# Device mapping strategy
device_map: auto

# LoRA configuration
lora:
  r: 16
  lora_alpha: 32
  target_modules: 
    - q_proj
    - k_proj
    - v_proj
    - o_proj
  lora_dropout: 0.05
  bias: none
  task_type: CAUSAL_LM
